version: '3.8'

services:
  inquisitor:
    build: .
    image: inquisitor
    container_name: inquisitor
    networks:
      - inquisitor

  ftpserver:
    image: stilliard/pure-ftpd:hardened
    container_name: ftpserver
    ports:
      # - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "127.0.0.1"
    networks:
      - inquisitor

  ftpclient:
    image: jlesage/filezilla
    container_name: ftpclient
    ports:
      - "5800:5800"
    volumes:
      - ./storage:/storage:rw
    networks:
      - inquisitor


networks:
  inquisitor:
