version: '3.8'

services:
  inquisitor:
    build: .
    image: inquisitor
    container_name: inquisitor
    networks:
      - inquisitor

  ftpserver:
    image: delfer/alpine-ftp-server
    container_name: ftpserver
    ports:
      - 21000-21010:21000-21010
    environment:
      - USERS=one|Qwertyuiop123
    volumes:
      - ./one:/ftp/one
    networks:
      - inquisitor

  ftpclient:
    image: jlesage/filezilla
    container_name: ftpclient
    ports:
      - "5800:5800"
    volumes:
      - ./storage:/storage:rw
    networks:
      - inquisitor


networks:
  inquisitor:
